### ISSUE TITLE
Feature: oEmbed Content

### ISSUE THREAD

**Issue by Vheissu** [SugarSteem/SugarSteem#18]
At present, Steemit.com and other Steem UI's lack support for many types of embeddable content with exception of images and YouTube videos.

Adding in [oEmbed](https://oembed.com/) support means we will be able to display embedded content in a nicer way. The lack of support for embedding Tweets on Steemit and Busy is really annoying, I hate having to take screenshots of tweets.

**Sites we'll support:**

- Giphy
- Youtube
- Vimeo
- CollegeHumor
- Flickr Videos and Images
- Imgur
- Instagram
- Kickstarter
- Mixcloud
- Photobucket
- Scribd
- SlideShare
- SmugMug
- SoundCloud
- Spotify
- Tumblr
- Twitter
- Reddit Comments

There might be some more we add to this list or some we remove, but this alone will allow for nicer formatted and looking posts, meaning users don't have to worry about screenshotting and uploading images. The downside to this is that only our UI will support oEmbed content. Maybe we can have some kind of fallback for other UI's like a link.

**Comment by theuxyeti** [comment]
This issue was moved to Vheissu/SugarSteem#3
