### ISSUE TITLE
Feature: Pixabay Media Embed (and picker)

### ISSUE THREAD

**Issue by Vheissu** [SugarSteem/SugarSteem#19]
As a Steem author, I routinely add images to my Steem posts from royalty-free site Pixabay. A feature for SugarSteem is a Pixabay media embed and picker. It could simply be a button on our WYSIWYG editor for posts that displays a modal with a search field and makes a search request, then pulls down the image and uploads it.

**Comment by theuxyeti** [comment]
This issue was moved to Vheissu/SugarSteem#2
