### ISSUE TITLE
Integrate functionality for parsing media for display posts

### ISSUE THREAD

**Issue by Vheissu** [SugarSteem/SugarSteem#20]
Steemit's Condenser application parses out all media from the content loaded from the Steem node. This allows it to strip out images, videos and so forth leaving only the content. It also removes links, etc because when you're wanting to parse out the excerpt it needs to ignore that content and get a section of text instead.

A situation where this helps is if a user puts an image first into their post and content beneath, we want to be able to get that content for a summary/excerpt style view. Steemit's code that does this is located here I believe: https://github.com/steemit/condenser/blob/master/src/app/utils/ExtractContent.js - but also possibly in other locations in other files.

This functionality will be used in numerous places, but most notable inside of the summary element located here: https://github.com/SugarSteem/SugarSteem/tree/master/src/components/content

I would consider adding in the functionality for doing this into the formatters file located here: https://github.com/SugarSteem/SugarSteem/blob/master/src/common/formatters.ts - or if you believe it should be a separate file, put it into `common` and name it appropriately.

**Comment by theuxyeti** [comment]
This issue was moved to Vheissu/SugarSteem#1
